### ISSUE TITLE
No pipeline jobs can be created anymore

### ISSUE THREAD

**Issue by MoritzWeber0** [DSD-DBS/capella-collab-manager#814]
```
time="2023-06-29 17:37:10,454" level=ERROR name=capellacollab.projects.toolmodels.backups.runs.interface function=_schedule_pending_jobs message="Scheduling of job run with id %s failed"
Traceback (most recent call last):
File "/tmp/backend/capellacollab/projects/toolmodels/backups/runs/interface.py", line 56, in _schedule_pending_jobs
job_name = operators.get_operator().create_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/backend/capellacollab/sessions/operators/k8s.py", line 458, in create_job
self._create_job(
TypeError: KubernetesOperator._create_job() got an unexpected keyword argument 'args'
```

The `args` argument is missing in `_create_job()`. The bug was introduced in https://github.com/DSD-DBS/capella-collab-manager/pull/793
